name: "Nix Build (linux) - with cachix upload"
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: rszyma
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build --print-build-logs
      - run: nix flake check --all-systems
      - run: nix fmt -- --ci